#' Plot cell type composition in each density level of cell of interest.
#'
#' @param spe A SpatialExperiment object.
#' @param coi A character vector of cell types of interest (COIs).
#' @param id A character. The name of the column of colData(spe) containing the 
#' cell type identifiers. Set to cell_type by default.
#' @param level_name The column name that generated by cellAssign.
#' @param seed Integer. Used for random color selection.
#' @param per_roi Logical. Default is FALSE, set to TRUE to allow plotting by ROI.
#'
#' @return A ggplot object.
#' @export
#'
#' @examples
#' 
#' data("xenium_bc_spe")
#' spe <- spe <- gridDensity(spe, coi = c("Breast cancer", "Fibroblasts"))
#' spe <- findROI(spe, coi = c("Breast cancer", "Fibroblasts"))
#' spe <- getContour(spe, coi = "Breast cancer")
#' spe <- cellAssign(spe, coi = "Breast cancer")
#' spe <- cellAssign(spe, assign = "roi", NA_level = "no_roi")
#' plotCellCompo(spe, coi = "Breast cancer")
#' plotCellCompo(spe, coi = "Breast cancer", per_roi = TRUE)
#' 
plotCellCompo <- function(spe, coi, id = "cell_type", 
                          level_name = paste0("at_level_", 
                                              janitor::make_clean_names(coi)),
                          seed = 33, per_roi = FALSE){
  
  dat <- as.data.frame(colData(spe))
  
  if(!(id %in% colnames(dat)) | !(level_name %in% colnames(dat))){
    stop("Parameter id and level_name are expected to be in the column names of
         the colData of spe.")
  }
  
  if(isFALSE(per_roi)){
    dat <- as.data.frame(colData(spe))[, c(id, level_name)]
  } else {
    if(!("at_rois" %in% colnames(dat))){
      stop("Column at_rois not found, please run cellAssign with assign=roi first.")
    }
    dat <- as.data.frame(colData(spe))[, c(id, level_name, "at_rois")]
  }

  if(!(coi %in% dat$cell_type)){
    stop("Parater coi is expected to be one of the cell types in the data.")
  }
  
  dat <- dat[dat$cell_type != coi,]
  
  if(isFALSE(per_roi)){
    toplot <- calc_proportions(dat, level_name, id)
  } else {
    dat <- dat[dat[["at_rois"]] != "no_roi",]
    
    grouped_data <- split(dat, as.character(dat[["at_rois"]]))
    
    proportions_by_roi <- lapply(grouped_data, function(group) {
      calc_proportions(group, level_name, id, per_roi)
    })
    
    toplot <- do.call(rbind, proportions_by_roi)
  }
  
  set.seed(seed)
  col.p <- randomcoloR::distinctColorPalette(3)
  
  p <- ggplot(toplot, aes(x = at_level_breast_cancer, 
                        y = Proportion, fill = cell_type)) +
    geom_bar(stat = "identity") + 
    scale_fill_manual("Cell type", values = col.p) + 
    ggtitle(paste0("Cell type composition at each ",coi," density level")) +
    theme_classic()
  
  if(isFALSE(per_roi)){
    return(p)
  } else {
    p <- p +
      facet_wrap(~at_rois)
    
    return(p)
  }
}

calc_proportions <- function(x, level_name, id, per_roi = FALSE) {
  cell_count <- table(x[[level_name]], x[[id]])
  cell_prop <- data.frame(prop.table(cell_count, margin = 1))
  colnames(cell_prop) <- c(level_name, id, "Proportion")
  cell_prop <- cell_prop[!is.na(cell_prop$Proportion),]
  if(isTRUE(per_roi)){
    cell_prop$at_rois <- unique(x[["at_rois"]])
  }
  return(cell_prop)
}





